version: '3.5'
services:

  express:
    build: .
    command: npm start
    ports:
      - "80:80"
      - "443:443"

  postgres:
    image: postgres:9.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bank
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    depends_on:
      - dbadmin

  dbadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "81:80"

volumes:
  postgres: